Warning: no access to tty (Bad file descriptor).
Thus no job control in this shell.
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:68: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:507: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3831: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3655: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3808: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3659: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/optimizers.py:757: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3069: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2021-03-26 20:43:08.057500: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-03-26 20:43:08.077070: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-03-26 20:43:10.102562: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ae608a5a820 executing computations on platform CUDA. Devices:
2021-03-26 20:43:10.102620: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla P100-PCIE-16GB, Compute Capability 6.0
2021-03-26 20:43:10.106156: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099970000 Hz
2021-03-26 20:43:10.106754: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2ae608acb010 executing computations on platform Host. Devices:
2021-03-26 20:43:10.106784: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-03-26 20:43:10.108279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:04:00.0
2021-03-26 20:43:10.110828: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.112912: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.114901: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.116833: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.118767: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.120676: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/intel64/broadwell/gcc/proj-5.2.0/lib:/usr/local/intel64/broadwell/intel/gdal-nograss-1.11.2/lib:/usr/local/cuda-9.1/lib64:/usr/local/cuda-9.1/lib64/stubd:/usr/local/cuda-9.1/nvvm/lib64:/lib64:/usr/lib64:/usr/local/intel64/broadwell/intel/openmpi-2.1.1-ib/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/compiler/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/tbb/lib/intel64/gcc4.4:/usr/local/intel-2017/debugger_2017/iga/lib:/usr/local/intel-2017/debugger_2017/libipt/intel64/lib:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/lib/intel64_lin:/usr/local/intel-2017/compilers_and_libraries_2017.0.098/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/gcc-5.2.0/lib:/usr/local/gcc-5.2.0/lib64:/usr/local/torque-6.1.1.1/lib:/usr/local/anaconda3-4.4.0/lib
2021-03-26 20:43:10.413758: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-03-26 20:43:10.413843: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2021-03-26 20:43:10.413891: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-26 20:43:10.413905: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-03-26 20:43:10.413917: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2021-03-26 20:43:12.435545: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
/usr/local/anaconda3-4.4.0/lib/python3.6/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/callbacks.py:774: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From /sciclone/home10/zlv/.local/bora/anaconda3/lib/python3.6/site-packages/keras/callbacks.py:777: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

Terminated
